# NumPy ProblemSet

In [1]:
# Intial code : Please execute this block before running any other codeblock
import numpy as np
import datetime

# Question 1. 
> Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
> Expected Output:
> Original List: [12.23, 13.32, 100, 36.32]
> One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [3]:
try:
    Original_list = [12.23, 13.32, 100, 36.32]
    print(f"Original-list : {Original_list}")

    numpy_array = np.array(Original_list)
    print(f"One-dimensional numpy array : {numpy_array}")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

Original-list : [12.23, 13.32, 100, 36.32]
One-dimensional numpy array : [ 12.23  13.32 100.    36.32]
Executed successfully on 2022-07-11 09:34:49.098786


# Question 2. 
> Create a 3x3 matrix with values ranging from 2 to 10.
> Expected Output:
> [[ 2 3 4]
> [ 5 6 7]
> [ 8 9 10]]

In [5]:
try:
    d = np.linspace(2, 10, 9, dtype=np.int64)
    d.shape = (3, 3)
    print(d)
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Executed successfully on 2022-07-11 09:36:55.843597


# Question 3. 
Write a Python program to create a null vector of size 10 and update sixth value to 11. \
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] \
Update sixth value to 11 \
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.] 

In [6]:
try:
    null_vector = np.zeros(10)
    print(f"Original Vector : \n{null_vector}")
    null_vector[6] = 11
    print(f"Update sixth value to 11 : \n{null_vector}")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

Original Vector : 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11 : 
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
Executed successfully on 2022-07-11 12:26:55.187306


# Question 4. 
> Write a Python program to reverse an array (first element becomes last). \
> Original array: \
> [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37] \
> Reverse array: \
> [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [7]:
try:
    d = np.linspace(12, 37, 38-12, dtype=np.int64)
    # d.shape = (3, 3)
    print(d)
    reverse_d = d[::-1]
    print(reverse_d)
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]
Executed successfully on 2022-07-11 12:28:38.001579


# Question 5. 
> Write a Python program to create a 2d array with 1 on the border and 0 inside. \
> Expected Output: \
> Original array: \
> [[ 1. 1. 1. 1. 1.]\
> [ 1. 1. 1. 1. 1.]\
> [ 1. 1. 1. 1. 1.]\
> [ 1. 1. 1. 1. 1.]\
> [ 1. 1. 1. 1. 1.]]\
> 1 on the border and 0 inside in the array\
> [[ 1. 1. 1. 1. 1.]\
> [ 1. 0. 0. 0. 1.]\
> [ 1. 0. 0. 0. 1.]\
> [ 1. 0. 0. 0. 1.]\
> [ 1. 1. 1. 1. 1.]]\

In [9]:
try:
    original_array = np.full((5,5), 1, dtype=float)
    output_array = original_array.copy()
    output_array[1:-1, 1:-1] = 0
    print(f"Original array : \n{original_array}")
    print(f"1 on the border and 0 inside in the array : \n{output_array}")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

Original array : 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array : 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Executed successfully on 2022-07-11 12:32:38.278226


# Question 6. 
> Write a Python program to add a border (filled with 0's) around an existing array. \
> Expected Output: \
> Original array:\
> [[ 1. 1. 1.]\
> [ 1. 1. 1.]\
> [ 1. 1. 1.]]\
> 1 on the border and 0 inside in the array\
> [[ 0. 0. 0. 0. 0.]\
> [ 0. 1. 1. 1. 0.]\
> [ 0. 1. 1. 1. 0.]\
> [ 0. 1. 1. 1. 0.]\
> [ 0. 0. 0. 0. 0.]]

In [10]:
# method 01
def add_borders_1(array_data):
    """
    1 on the border and 0 inside in the array
    Args:
        array_data (_type_): ndArray of order nxm
    """
    output_array = np.resize(array_data, (5, 5))
    output_array[0:-1, 0] = 0
    output_array[0:-1, -1] = 0
    output_array[0,:] = 0
    output_array[-1,:] = 0
    return output_array
    

# method 02
def add_borders_2(array_data):
    """
    1 on the border and 0 inside in the array
    Args:
        array_data (_type_): ndArray of order nxm
    """
    return np.pad(array_data, pad_width=1, mode="constant", constant_values=0)

In [11]:
try:
    original_array = np.ones((3,3), dtype=float)
    print(f"\n----------------------------------------------\n")
    print(f"add_borders_method_01 : \n{add_borders_1(original_array)}")
    print(f"\n----------------------------------------------\n")
    print(f"add_borders_method_02 : \n{add_borders_2(original_array)}")
    print(f"\n----------------------------------------------\n")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------------------------

add_borders_method_01 : 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

----------------------------------------------

add_borders_method_02 : 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

----------------------------------------------

Executed successfully on 2022-07-11 12:36:19.193941


# Question 7. 
> Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.\
> Checkerboard pattern:\
> [[0 1 0 1 0 1 0 1]\
> [1 0 1 0 1 0 1 0]\
> [0 1 0 1 0 1 0 1]\
> [1 0 1 0 1 0 1 0]\
> [0 1 0 1 0 1 0 1]\
> [1 0 1 0 1 0 1 0]\
> [0 1 0 1 0 1 0 1]\
> [1 0 1 0 1 0 1 0]]

In [12]:
def checkerboard_pattern(data_array):
    """_summary_

    Args:
        data_array (_type_): _description_

    Returns:
        _type_: _description_
    """
    temp = data_array.copy()
    temp[1::2, ::2] = 1
    temp[::2, 1::2] = 1
    return temp

In [14]:
try:
    base_array = np.zeros((8,8), dtype=int)
    #print(base_array)
    final_array_1 = checkerboard_pattern(base_array)
    print(final_array_1)
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Executed successfully on 2022-07-11 12:39:16.923545


# Question 8. 
> Write a Python program to convert a list and tuple into arrays.\
> List to array:\
> [1 2 3 4 5 6 7 8]\
> Tuple to array:\
> [[8 4 6]\
> [1 2 3]]

In [15]:
def to_array(array_data):
    """_summary_

    Args:
        array_data (_type_): _description_
    """
    return np.array(array_data)

try:
    list_data = [i for i in range(1,9)]
    list_to_array = to_array(list_data)
    print(f"List to Array conversion : {list_to_array} and type of data : {type(list_to_array)} and shape of data : {list_to_array.shape}")
    tuple_data = ([8, 4, 6], [1, 2, 3])
    tuple_to_array = to_array(tuple_data)
    print(f"Tuple to Array conversion : {tuple_to_array} and type of data : {type(tuple_to_array)} and shape of data : {tuple_to_array.shape}")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

List to Array conversion : [1 2 3 4 5 6 7 8] and type of data : <class 'numpy.ndarray'> and shape of data : (8,)
Tuple to Array conversion : [[8 4 6]
 [1 2 3]] and type of data : <class 'numpy.ndarray'> and shape of data : (2, 3)
Executed successfully on 2022-07-11 12:47:58.906417


# Question 9. 
> Write a Python program to append values to the end of an array.\
> Expected Output:\
> Original array:\
> [10, 20, 30]\
> After append values to the end of the array:\
> [10 20 30 40 50 60 70 80 90]

In [17]:
try:
    original_array = np.array([10, 20, 30])
    print("\n---------------------------------\n")
    print("Original array : \n",original_array)
    print("\n---------------------------------\n")
    final_array = np.append(original_array, [40, 50 ,60, 70, 80, 90])
    # original_array.append(np.array([40, 50, 60]))
    print("After append values to the end of the array: \n",final_array)
    print("\n---------------------------------\n")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


---------------------------------

Original array : 
 [10 20 30]

---------------------------------

After append values to the end of the array: 
 [10 20 30 40 50 60 70 80 90]

---------------------------------

Executed successfully on 2022-07-11 12:51:38.561388


# Question 10. 
> Write a Python program to find the real and imaginary parts of an array of complex\
> numbers.\
> Expected Output:\
> Original array [ 1.00000000+0.j 0.70710678+0.70710678j]\
> Real part of the array:\
> [ 1. 0.70710678]\
> Imaginary part of the array:\
> [ 0. 0.70710678]

In [18]:
try:
    Original_array = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
    print("\n-----------------------------------------------\n")
    print("The original array is : ",Original_array)
    print(f"The real parts of the array are : {Original_array.real}")
    print(f"The imaginary parts of the array are : {Original_array.imag}")
    print("\n-----------------------------------------------\n")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


-----------------------------------------------

The original array is :  [1.        +0.j         0.70710678+0.70710678j]
The real parts of the array are : [1.         0.70710678]
The imaginary parts of the array are : [0.         0.70710678]

-----------------------------------------------

Executed successfully on 2022-07-11 12:53:21.346591


# Question 11. 
> Write a Python program to find the number of elements of an array, length of one\
> array element in bytes and total bytes consumed by the elements.\
> Expected Output:\
> Size of the array: 3\
> Length of one array element in bytes: 8\
> Total bytes consumed by the elements of the array: 24

In [19]:
try:
    demo_list = list(range(101,104))
    original_array = np.array(demo_list, dtype=np.float64)
    print("\n------------------------------------------\n")
    print("Size of the array: ", original_array.size)
    print("Length of one array element in bytes: ", original_array.itemsize)
    print("Total bytes consumed by the elements of the array: ", original_array.nbytes)
    print("\n------------------------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


------------------------------------------

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24

------------------------------------------

Executed successfully on 2022-07-11 12:54:59.870312


# Question 12. 
> Write a Python program to find common values between two arrays.\
> Expected Output:\
> Array1: [ 0 10 20 40 60]\
> Array2: [10, 30, 40]\
> Common values between two arrays:\
> [10 40]

In [21]:
def common_values(array_data1, array_data2):
    return np.intersect1d(array_data1, array_data2)


try:
    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])
    print("\n--------------------------------------\n")
    print(f"Array1 : {array1}")
    print(f"Array2 : {array2}")
    common_array = common_values(array1, array2)
    print(f"Common values between two arrays: \n{common_array}")
    print("\n--------------------------------------\n")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


--------------------------------------

Array1 : [ 0 10 20 40 60]
Array2 : [10 30 40]
Common values between two arrays: 
[10 40]

--------------------------------------

Executed successfully on 2022-07-11 12:58:53.235451


# Question 13. 
> Write a Python program to find the set difference of two arrays. The set difference\
> will return the sorted, unique values in array1 that are not in array2.\
> Expected Output:\
> Array1: [ 0 10 20 40 60 80]\
> Array2: [10, 30, 40, 50, 70, 90]\
> Set difference between two arrays: [ 0 20 60 80]

In [22]:
def diff_values(array_data1, array_data2):
    return np.setdiff1d(array_data1, array_data2)


try:
    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70, 90])

    print("\n--------------------------------------\n")
    print(f"Array1 : {array1}")
    print(f"Array2 : {array2}")
    common_array = diff_values(array1, array2)
    print(f"Set difference between two arrays: {common_array}")
    print("\n--------------------------------------\n")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


--------------------------------------

Array1 : [ 0 10 20 40 60 80]
Array2 : [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]

--------------------------------------

Executed successfully on 2022-07-11 13:22:52.210617


# Question 14. 
> Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or\
> will return the sorted, unique values that are in only one (not both) of the input arrays.\
> Array1: [ 0 10 20 40 60 80]\
> Array2: [10, 30, 40, 50, 70]\
> Unique values that are in only one (not both) of the input arrays:\
> [ 0 20 30 50 60 70 80]

In [23]:
def exclusive_values(array_data1, array_data2):
    return np.setxor1d(array_data1, array_data2)


try:
    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70])

    print("\n--------------------------------------\n")
    print(f"Array1 : {array1}")
    print(f"Array2 : {array2}")
    unique_array = np.setxor1d(array1, array2)
    print(f"Unique values that are in only one (not both) of the input arrays: \n{unique_array}")
    print("\n--------------------------------------\n")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


--------------------------------------

Array1 : [ 0 10 20 40 60 80]
Array2 : [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays: 
[ 0 20 30 50 60 70 80]

--------------------------------------

Executed successfully on 2022-07-11 14:37:01.964409


# Question 15. 
> Write a Python program compare two arrays using numpy.\
> Array a: [1 2]\
> Array b: [4 5]\
> a > b\
> [False False]\
> a >= b\
> [False False]\
> a < b\
> [ True True]\
> a <= b\
> [ True True] 

In [24]:
try:
    array_a = np.array([1, 2])
    array_b = np.array([4, 5])
    print("\n----------------------------------\n")
    print(f"Array a : {array_a}")
    print(f"Array b : {array_b}")
    print(f"a > b : \n{array_a > array_b}")
    print(f"a >= b : \n{array_a >= array_b}")
    print(f"a < b : \n{array_a < array_b}")
    print(f"a <= b : \n{array_a <= array_b}")
    print("\n----------------------------------\n")
    
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------------

Array a : [1 2]
Array b : [4 5]
a > b : 
[False False]
a >= b : 
[False False]
a < b : 
[ True  True]
a <= b : 
[ True  True]

----------------------------------

Executed successfully on 2022-07-11 14:38:23.874467


# Question 16. 
> Write a Python program to create a contiguous flattened array.\
> Original array:\
> [[10 20 30]\
> [20 40 50]]\
> New flattened array:\
> [10 20 30 20 40 50]

In [25]:
original_array = np.array([[10, 20, 30], [20, 40, 50]])
try:
    print("\n---------------------------------\n")
    print(f"Original array : \n{original_array}")
    flattened_array = np.ravel(original_array, order='C')
    print(f"New Flattened array : \n{flattened_array}")
    print("\n---------------------------------\n")
    
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


---------------------------------

Original array : 
[[10 20 30]
 [20 40 50]]
New Flattened array : 
[10 20 30 20 40 50]

---------------------------------

Executed successfully on 2022-07-11 14:51:36.656166


# Question 17. 
> Write a Python program to change the data type of an array.\
> Expected Output:\
> [[ 2 4 6]\
> [ 6 8 10]]\
> Data type of the array x is: int32\
> New Type: float64\
> [[ 2. 4. 6.]\
> [ 6. 8. 10.]]

In [26]:
original_array = np.array([[2, 4, 6], [6, 8, 10]])
try:
    print("\n---------------------------------\n")
    print(f"Expected Output: \n{original_array}")
    print(f"Data type of the array x is: {original_array.dtype}")
    new_array = original_array.astype(np.float64)
    print(f"New Type: {new_array.dtype}")
    print(f"New array : \n{new_array}")
    print("\n---------------------------------\n")
    
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


---------------------------------

Expected Output: 
[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type: float64
New array : 
[[ 2.  4.  6.]
 [ 6.  8. 10.]]

---------------------------------

Executed successfully on 2022-07-11 14:53:15.316084


# Question 18. 
> Write a Python program to create a 3-D array with ones on a diagonal and zeros\
> elsewhere.\
> Expected Output:\
> [[ 1. 0. 0.]\
> [ 0. 1. 0.]\
> [ 0. 0. 1.]]

In [27]:
try:
    identity_array = np.eye(3)
    print("\n---------------------------------\n")
    print(f"Expected Output: \n{identity_array}")
    print("\n---------------------------------\n")
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


---------------------------------

Expected Output: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

---------------------------------

Executed successfully on 2022-07-11 14:55:34.736770


# Question 19. 
> Write a Python program to create an array which looks like below array.\
> Expected Output:\
> [[ 0. 0. 0.]\
> [ 1. 0. 0.]\
> [ 1. 1. 0.]\
> [ 1. 1. 1.]]

In [28]:
try:
    demo_array = np.zeros((4,3))
    count = 1
    while count<len(demo_array):
        demo_array[count,:count] = 1
        count +=1    
    print(f"\n--------------------------------------\n")
    print(f"Expected Output 1 : \n{demo_array}")
    print(f"\n--------------------------------------\n")
    print(f"Expected Output 2 : \n{np.tri(4, 3, -1)}")
    print(f"\n--------------------------------------\n")    
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


--------------------------------------

Expected Output 1 : 
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]

--------------------------------------

Expected Output 2 : 
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]

--------------------------------------

Executed successfully on 2022-07-11 14:56:29.607014


# Question 20. 
> Write a Python program to concatenate two 2-dimensional arrays.\
> Expected Output:\
> Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]\
> Expected Output:\
> [[ 0 1 3 0 2 4]\
> [ 5 7 9 6 8 10]]

In [29]:
array_a = np.array([[0, 1, 3], [5, 7, 9]])
array_b = np.array([[0, 2, 4], [6, 8, 10]])

try:
    print("\n----------------------------\n")
    print(f"Sample arrays: {array_a.tolist(), array_b.tolist()}")
    print("\n----------------------------\n")
    output_array_1 = np.concatenate([array_a, array_b], axis=0)
    print(f"Expected Output 1 with axis 0 : \n{output_array_1}")
    output_array_2 = np.concatenate([array_a, array_b], axis=1)
    print(f"Expected Output 2 with axis 1 : \n{output_array_2}")
    print("\n----------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------

Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])

----------------------------

Expected Output 1 with axis 0 : 
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]
Expected Output 2 with axis 1 : 
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]

----------------------------

Executed successfully on 2022-07-11 14:57:43.421487


# Question 21. 
> Write a Python program to make an array immutable (read-only).\
> Expected Output:\
> Test the array is read-only or not:\
> Try to change the value of the first element:\
> Traceback (most recent call last):\
> File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in\
> x[0] = 1\
> ValueError: assignment destination is read-only

In [30]:
try:
    sample_array = np.array([21, 43, 13, 46])
    sample_array.flags.writeable = False
    print(f"Test the array is read-only or not : ")
    print(f"Try to change the value of the first element : ")
    sample_array[0] = 1
except Exception as e:
    print(f"Error : {e}")
else:
    print(f"Executed successfully on {datetime.datetime.now()}")

Test the array is read-only or not : 
Try to change the value of the first element : 
Error : assignment destination is read-only


# Question 22. 
> Write a Python program to create an array of (3, 4) shape, multiply every element\
> value by 3 and display the new array.\
> Expected Output:\
> Original array elements:\
> [[ 0 1 2 3]\
> [ 4 5 6 7]\
> [ 8 9 10 11]]\
> New array elements:\
> [[ 0 3 6 9]\
> [12 15 18 21]\
> [24 27 30 33]]

In [31]:
try:
    original_array = np.array(list(range(12)))
    original_array = original_array.reshape(3,4) 
    print("\n---------------------------------\n")
    print(f"Original array elements : \n{original_array}")
    print("\n---------------------------------\n")
    multiplied_array = original_array * 3
    print(f"New array elements : \n{multiplied_array}")
    print("\n---------------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


---------------------------------

Original array elements : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

---------------------------------

New array elements : 
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]

---------------------------------

Executed successfully on 2022-07-11 15:03:02.393682


# Question 23. 
> Write a Python program to convert a NumPy array into Python list structure.\
> Expected Output:\
> Original array elements:\
> [[0 1]\
> [2 3]\
> [4 5]]\
> Array to list:\
> [[0, 1], [2, 3], [4, 5]]

In [32]:
original_array = np.array([[0, 1], [2, 3], [4, 5]])

try:
    print("\n----------------------------\n")
    print(f"Original array elements: \n{original_array}")
    print("\n----------------------------\n")
    print(f"Array to list : \n{original_array.tolist()}")
    print("\n----------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------

Original array elements: 
[[0 1]
 [2 3]
 [4 5]]

----------------------------

Array to list : 
[[0, 1], [2, 3], [4, 5]]

----------------------------

Executed successfully on 2022-07-11 15:03:59.111270


# Question 24. 
> Write a Python program to convert a NumPy array into Python list structure.\
> Expected Output:\
> Original array elements:\
> [ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349\
> 0.35399976 0.99469633 0.0694458 0.54711478]\
> Print array values with precision 3:\
> [ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [33]:
original_array = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])

try:
    print("\n----------------------------\n")
    print(f"Original array elements: \n{original_array}")
    print("\n----------------------------\n")
    print(f"Print array values with precision 3 : \n{[round(i, 3) for i in original_array.tolist()]}")
    print("\n----------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------

Original array elements: 
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]

----------------------------

Print array values with precision 3 : 
[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]

----------------------------

Executed successfully on 2022-07-11 15:04:58.582510


# Question 25. 
> Write a Python program to suppresses the use of scientific notation for small\
> numbers in numpy array.\
> Expected Output:\
> Original array elements:\
> [ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]\
> Print array values with precision 3:\
> [ 0. 1.6 1200. 0.235]

In [34]:
original_array = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])

try:
    print("\n----------------------------\n")
    print(f"Original array elements: \n{original_array}")
    print("\n----------------------------\n")
    np.set_printoptions(precision=3, suppress=True)
    print(f"Print array values with precision 3 : \n{original_array}")
    print("\n----------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------

Original array elements: 
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]

----------------------------

Print array values with precision 3 : 
[   0.       1.6   1200.       0.235]

----------------------------

Executed successfully on 2022-07-11 15:05:51.680300


# Question 26. 
> Write a Python program to how to add an extra column to an numpy array.\
> Expected Output:\
> [[ 10 20 30 100]\
> [ 40 50 60 200]]

In [35]:
original_array = np.array([[10, 20, 30],[40, 50 ,60]])
column_to_add = np.array([100, 200])

try:
    print("\n----------------------------\n")
    print(f"Original array elements: \n{original_array}")
    print("\n----------------------------\n")
    output_array = np.c_[original_array, column_to_add]
    print(f"Expected Output : \n{output_array}")
    print("\n----------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------

Original array elements: 
[[10 20 30]
 [40 50 60]]

----------------------------

Expected Output : 
[[ 10  20  30 100]
 [ 40  50  60 200]]

----------------------------

Executed successfully on 2022-07-11 15:06:52.571318


# Question 27. 
> Write a Python program to remove specific elements in a numpy array.\
> Expected Output:\
> Original array:\
> [ 10 20 30 40 50 60 70 80 90 100]\
> Delete first, fourth and fifth elements:\
> [ 20 30 60 70 80 90 100]

In [37]:
original_array = np.linspace(10, 100, 10, dtype=int)
try:
    print("\n----------------------------\n")
    print(f"Original array: \n{original_array}")
    print("\n----------------------------\n")
    output_array = np.delete(original_array, [0, 3, 4])
    print(f"Delete first, fourth and fifth elements : \n{output_array}")
    print("\n----------------------------\n")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------

Original array: 
[ 10  20  30  40  50  60  70  80  90 100]

----------------------------

Delete first, fourth and fifth elements : 
[ 20  30  60  70  80  90 100]

----------------------------

Executed successfully on 2022-07-11 15:08:23.985690


# Question 28. 
> Write a Python program to save a NumPy array to a text file.

In [38]:
original_array = np.linspace(10, 1000, 25, dtype=int)

try:
    print("\n----------------------------\n")
    print(f"Original array: \n{original_array}")
    print("\n----------------------------\n")
    output_array = np.reshape(original_array, (5,5))
    print(f"Output Array : \n{output_array}")
    print("\n----------------------------\n")
    np.savetxt("q28_output.txt",output_array, delimiter=" ", header="Question 28 Solution Array")
except Exception as e:
    print("Error : ",e)
else:
    print(f"Executed successfully on {datetime.datetime.now()}")


----------------------------

Original array: 
[  10   51   92  133  175  216  257  298  340  381  422  463  505  546
  587  628  670  711  752  793  835  876  917  958 1000]

----------------------------

Output Array : 
[[  10   51   92  133  175]
 [ 216  257  298  340  381]
 [ 422  463  505  546  587]
 [ 628  670  711  752  793]
 [ 835  876  917  958 1000]]

----------------------------

Executed successfully on 2022-07-11 15:09:30.892482
